[supabase]
url = "Aapki_Asli_URL_Yahan_Daalein"
key = "Aapki_Asli_Key_Yahan_Daalein"

[app]
password = "Vision@2026"

[cloudinary]
cloud_name = "mtijo4zl"
api_key = "831329926139992"
api_secret = "eSbAuyDnjQ_j2A4k0HIBCv3-25o"
